Repository 2022-Alpha-Daesin/daesin_front, pull requests merged in 2022-11, with the labels that each got.

#12 Feature/11 query
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/components/Common/FlexTextBox.jsx
  src/index.js
Labels: 💡Feature

#9 Feature/8 responsive layout
  package-lock.json
  package.json
  src/layouts/desktop.layout.jsx
  src/layouts/maxWidth.layout.jsx
  src/layouts/mobile.layout.jsx
  src/layouts/responsive.layout.jsx
Labels: 💡Feature

#16 Feature/14 header
  package-lock.json
  package.json
  src/App.js
  src/components/Common/FlexBox.jsx
  src/components/Navbar/DesktopNavbar.jsx
  src/components/Navbar/Searchbar.jsx
  src/layouts/desktop.layout.jsx
  src/styles/GlobalStyles.js
Labels: 💡Feature

#18 Feature/15 crew card
  public/images/sample.png
  src/components/Card/CrewCard.jsx
  src/components/Card/CrewCardWrapper.jsx
  src/components/Common/FlexTextBox.jsx
  src/layouts/maxWidth.layout.jsx
Labels: 💡Feature

#19 Feature/17 login UI
  package-lock.json
  package.json
  src/App.js
  src/components/Navbar/DesktopNavbar.jsx
  src/pages/SignIn/SignIn.js
Labels: 💡Feature

#26 feat: SingUp 초안
  package-lock.json
  src/App.js
  src/components/Navbar/DesktopNavbar.jsx
  src/pages/SignIn/SignIn.jsx
  src/pages/Signup/SignUp.jsx
Labels: 💡Feature

#24 feat: FlexButton
  src/components/Common/FlexButton.jsx
Labels: 💡Feature

#28 Feature/20 sign up
  src/constants/MajorData.js
  src/pages/SignIn/SignIn.jsx
  src/pages/Signup/SignUp.jsx
Labels: 💡Feature

#29 Feature/22 club layout
  src/App.js
  src/components/Common/FlexButton.jsx
  src/components/Common/FlexTextBox.jsx
  src/components/Crew/Card/CrewCard.jsx
  src/components/Crew/Card/CrewCardWrapper.jsx
  src/components/Crew/Card/CrewCategory.jsx
  src/components/Navbar/DesktopNavbar.jsx
  src/constants/color.js
  src/layouts/desktop.layout.jsx
  src/layouts/maxWidth.layout.jsx
  src/pages/Club/Club.jsx
  src/styles/GlobalStyles.js
Labels: 💡Feature

#32 feat: ClubDetailCard
  src/components/Club/Card/ClubCard.jsx
  src/components/Club/Card/ClubCardWrapper.jsx
  src/components/Club/Card/ClubCategory.jsx
  src/components/Club/Card/ClubDetailCard.jsx
  src/components/Club/Card/dummyData.js
  src/components/Common/FlexTextBox.jsx
  src/components/Crew/Card/CrewCardWrapper.jsx
  src/pages/Club/Club.jsx
Labels: 💡Feature

#34 feat: ClubDetailLayout
  src/App.js
  src/components/Club/Card/ClubDetailCardWrapper.jsx
  src/layouts/maxWidth.layout.jsx
  src/pages/Club/ClubDetail.jsx
Labels: 💡Feature, 🎨InReview

#38 Feature/36 ad date tab
  package-lock.json
  package.json
  src/components/AD/ADDateTab.jsx
  src/components/Club/Card/ClubCategory.jsx
  src/constants/color.js
  src/hooks/useDate.js
  src/pages/Club/Club.jsx
Labels: 💡Feature, 🎨InReview

#44 홍보 메인페이지
  src/components/AD/ADCard.jsx
  src/components/AD/ADCardWrapper.jsx
  src/components/AD/ADCarousel.jsx
  src/components/AD/ADCategory.jsx
  src/components/AD/ADDateTab.jsx
  src/pages/AD/AD.jsx
Labels: 💡Feature, 🎨InReview

#46 feat: 홍보 article
  public/images/ADArticle.png
  src/components/Common/FlexBox.jsx
  src/components/Navbar/Searchbar.jsx
  src/pages/AD/ADArticle.jsx
Labels: 💡Feature

#48 Feature/47 ad article modal
  src/components/AD/ADArticleModal.jsx
  src/components/Common/FlexTextArea.jsx
  src/components/Common/index.js
  src/constants/color.js
  src/pages/AD/AD.jsx
Labels: 💡Feature

#49 Feature/30 sign up query
  .env
  package-lock.json
  package.json
  src/App.js
  src/apis/config.js
  src/apis/userAPI.js
  src/apis/userRelatedAPI.js
  src/components/Navbar/DesktopNavbar.jsx
  src/constants/URLS.js
  src/hooks/useInput.js
  src/index.js
  src/pages/SignIn/SignIn.jsx
  src/pages/Signup/SignUp.jsx
  src/queries/auth/useSignInMutation.js
  src/queries/auth/useSignUpMutation.js
  src/states/index.js
  src/states/userinfo.js
Labels: 💡Feature

#52 feat: 날짜 캘린더로 선택 + 커스텀
  package-lock.json
  package.json
  src/components/AD/ADArticleModal.jsx
  src/components/AD/datepicker.css
Labels: 💡Feature

#57 Feature/51 toast msg
  package-lock.json
  package.json
  src/constants/message.js
  src/pages/SignIn/SignIn.jsx
  src/pages/Signup/SignUp.jsx
  src/queries/auth/useSignInMutation.js
  src/queries/auth/useSignUpMutation.js
  src/states/userInfo.js
Labels: enhancement

#62 feat: 실시간 검색어 컴포넌트, NOW 페이지 레이아웃
  package-lock.json
  src/components/Now/FoodMenuCard.jsx
  src/components/Now/FoodMenuCarousel.jsx
  src/components/Now/HotKeyword.jsx
  src/constants/color.js
  src/pages/Now/Now.jsx
Labels: 💡Feature

#64 Feature/58 review post modal
  package-lock.json
  src/components/Review/ReviewCategory.jsx
  src/components/Review/ReviewPostList.jsx
  src/components/Review/ReviewPostModal.jsx
  src/pages/Review/Review.jsx
Labels: 💡Feature

#65 Feature/59 review detail page
  src/App.js
  src/components/Common/FlexBox.jsx
  src/components/Common/FlexTextBox.jsx
  src/components/Review/ReviewPostList.jsx
  src/components/ReviewDetail/AddComment.jsx
  src/components/ReviewDetail/CommentList.jsx
  src/components/ReviewDetail/CommentReply.jsx
  src/pages/ReviewDetail/ReviewDetail.jsx
Labels: 💡Feature

#71 Feature/69 category fix
  src/components/AD/ADCategory.jsx
  src/components/AD/ADDateTab.jsx
  src/components/Club/DummyData.js
Labels: 🔨Refactor

#75 Feature/68 review comment reply UI
  src/components/ReviewDetail/AddCommentReply.jsx
  src/components/ReviewDetail/CommentList.jsx
  src/components/ReviewDetail/CommentReply.jsx
  src/pages/ReviewDetail/ReviewDetail.jsx
Labels: 💡Feature

#76 style: navbar position fixed
  src/components/Navbar/DesktopNavbar.jsx
  src/layouts/desktop.layout.jsx
Labels: 💡Feature

#73 Feature/60 authorization
  .env
  package-lock.json
  package.json
  src/App.js
  src/apis/config.js
  src/apis/majorAPI.js
  src/apis/userRelatedAPI.js
  src/components/Navbar/DesktopNavbar.jsx
  src/constants/URLS.js
  src/constants/message.js
  src/index.js
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/styles.js
  src/pages/Signup/SignUp.jsx
  src/pages/Signup/styles.js
  src/queries/auth/index.js
  src/queries/auth/useRefreshMutation.js
  src/queries/auth/useSignInMutation.js
  src/queries/auth/useSignUpMutation.js
  src/queries/auth/useVerifyEmailMutation.js
  src/queries/major/index.js
  src/queries/major/useCollegeQuery.js
  src/queries/major/useMajorQuery.js
  src/states/userInfo.js
Labels: 💡Feature

#80 feat: kookmin.ac.kr로 로그인 안할 시 toast error message 처리
  src/pages/SignIn/SignIn.jsx
  src/queries/auth/useSignInMutation.js
Labels: 💡Feature

#82 Feature/81 sign up exceptions
  src/App.js
  src/apis/config.js
  src/pages/SignIn/SignIn.jsx
  src/pages/Signup/SignUp.jsx
  src/queries/auth/useRefreshMutation.js
  src/queries/auth/useSignUpMutation.js
  src/utils/SignUpHandler.js
  src/utils/SignUpMutationHandler.js
Labels: 💡Feature
